micronaut:
  application:
    name: graphqlPayments
  security:
    enabled: false
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: '"${JWT_GENERATOR_SIGNATURE_SECRET:somesecret}"'


graphql:
  enabled: true
  path: /graphql

  graphiql:
    enabled: true
    path: /graphiql
    template-parameters:
    page-title: GraphQL Payments